distributable: ~

# TODO: build from source (complicated)
warnings: [vendored]

display-name: scie-pants

versions:
  - 0.12.0

# patch RPATH has occurred segment fault error
build:
  dependencies:
    curl.se: "*"
  script: |
    curl -Lfo pants https://github.com/pantsbuild/scie-pants/releases/download/v{{version}}/scie-pants-$PLATFORM
    chmod u+x pants
    mkdir -p "{{prefix}}/bin"
    cp -a pants "{{prefix}}/bin"
  skip: fix-patchelf
  env:
    darwin/aarch64:
      PLATFORM: macos-aarch64
    darwin/x86-64:
      PLATFORM: macos-x86_64
    linux/aarch64:
      PLATFORM: linux-aarch64
    linux/x86-64:
      PLATFORM: linux-x86_64

provides:
  - bin/pants

test:
  script: |
    cat << EOF > pants.toml
    [GLOBAL]
    pants_version = "2.17.1"
    EOF
    test "$(pants --version)" = 2.17.1
